name: Build test
on: [push]

jobs:
  linux64:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.filenames.outputs.longversion }}
      do-docker: ${{ steps.filenames.outputs.branch }}
    steps:
      - name: Test
        id: filenames
        shell: bash
        run: |
          #echo "branch=stable" >> $GITHUB_OUTPUT
          echo "branch=beta" >> $GITHUB_OUTPUT
          echo "longversion=3.1.0+6223-stable-1b6dfc49" >> $GITHUB_OUTPUT


  docker-image:
    runs-on: ubuntu-latest

    needs:
      - linux64

    env:
      IMAGE_NAME: test

    steps:
      - uses: actions/checkout@v3
        if: ${{ needs.linux64.outputs.do-docker }}

      - name: Determine target image name
        if: ${{ needs.linux64.outputs.do-docker }}
        id: image-name
        run: |
          BUILD_VERSION=${{ needs.linux64.outputs.version }}

          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME

           # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          IMAGES=
          IMAGES="$IMAGE_ID:$VERSION,$IMAGES"
          # IMAGES="$IMAGE_ID:$BUILD_VERSION,$IMAGES" TODO - this would be nice to have, but the version needs making docker-tag safe first

          # debug output
          echo images $IMAGES
          echo "images=$IMAGES" >> $GITHUB_OUTPUT
          echo "build_version=$BUILD_VERSION" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/$IMAGE_NAME
          tags: |
            type=raw,value=${{ needs.linux64.outputs.version }}
            type=ref,event=tag

      - name: Set up QEMU
        if: ${{ steps.image-name.outputs.images }}
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: ${{ steps.image-name.outputs.images }}
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        if: ${{ steps.image-name.outputs.images }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        if: ${{ steps.image-name.outputs.images }}
        with:
          context: .
          file: Dockerfile.prebuild
          platforms: linux/amd64,linux/arm64/v8
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: "${{ steps.meta.outputs.tags }}"
          build-args: |
            build_name=${{ steps.image-name.outputs.build_version }}
