name: Build test
on: 
    - push
    - workflow_dispatch

jobs:
  linux64:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.filenames.outputs.longversion }}
      do-docker: ${{ steps.filenames.outputs.branch }}
    steps:
      - name: Test
        id: filenames
        shell: bash
        run: |
          echo "OK"
          #echo "branch=stable" >> $GITHUB_OUTPUT
          echo "branch=beta" >> $GITHUB_OUTPUT
          echo "longversion=3.1.0+6223-stable-1b6dfc49" >> $GITHUB_OUTPUT


  docker-image:
    runs-on: ubuntu-latest

    needs:
      - linux64

    env:
      IMAGE_NAME: test

    steps:
      - uses: actions/checkout@v3
        if: ${{ needs.linux64.outputs.do-docker }}

      - name: Docker meta
        if: ${{ needs.linux64.outputs.do-docker }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/$IMAGE_NAME
          tags: |
            type=raw,value=${{ needs.linux64.outputs.version }}
            type=ref,event=tag

      - name: Set up QEMU
        if: ${{ steps.meta.outputs.tags }}
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: ${{ steps.meta.outputs.tags }}
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        if: ${{ steps.meta.outputs.tags }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        if: ${{ steps.meta.outputs.tags }}
        with:
          context: .
          file: Dockerfile.prebuild
          platforms: linux/amd64,linux/arm64/v8
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: "${{ steps.meta.outputs.tags }}"
          build-args: |
            build_name=${{ needs.linux64.outputs.version }}
